#!/usr/bin/env bash
set -euo pipefail

BM_VERSION=0.1.0
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config/}"
BOOKMARKS_DIR="${XDG_CONFIG_HOME}/bm"
BM="$0"
COMMAND="${1:-""}"

if [ ! -d "${BOOKMARKS_DIR}" ]; then
  mkdir -p "${BOOKMARKS_DIR}"
fi

LS=${LS:-exa}
if ! which exa >/dev/null 2>&1; then
  LS="ls"
fi

case "$COMMAND" in
  --help)
    echo "bm --expand|--preview|--resolve|--list"
    ;;
  -v|--version)
    echo "bm $BM_VERSION"
    ;;
  --expand)
    export FZF_DEFAULT_OPTS="--preview '$BM --preview {}' --prompt 'jump to: '"

    # Failsafe if fzf fails/escapes prematurely
    set +e
    BOOKMARK=$(ls -1 "${BOOKMARKS_DIR}" | fzf)
    RETURNVALUE=$?
    set -e

    if [ "${BOOKMARK}" = "" ]; then
      echo "."
    else
      $BM --resolve "${BOOKMARK}"
    fi
    ;;

  --preview)
    BOOKMARK="${2:-}"
    RESOLVED="$($BM --resolve "${BOOKMARK}")"
    echo "$(tput smul; tput bold)${RESOLVED}$(tput sgr0)"
    $LS -1 "${RESOLVED}"
    ;;

  --resolve)
    BOOKMARK=${2:-}
    readlink -f ${BOOKMARKS_DIR}/${BOOKMARK}
    ;;

  --list)
    if [ "$LS" = "exa" ]; then
      $LS -1 ${BOOKMARKS_DIR}
    else
      $LS -1 ${BOOKMARKS_DIR} | while read BOOKMARK; do
        echo "${BOOKMARK}: $($BM --resolve "${BOOKMARK}")"
      done
    fi
    ;;

  *|"")
    ln -s "$(realpath .)" "${BOOKMARKS_DIR}/${COMMAND}"
    ;;
esac
