#!/usr/bin/env bash
set -euo pipefail

BM_VERSION=0.1.0
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config/}"
BOOKMARKS_DIR="${XDG_CONFIG_HOME}/bm"
BM="$0"
COMMAND="${1:-""}"

if [ ! -d "${BOOKMARKS_DIR}" ]; then
  mkdir -p "${BOOKMARKS_DIR}"
fi

LS=${LS:-exa}
if ! which exa >/dev/null 2>&1; then
  LS="ls"
fi

function bm_pick_bookmark() {
  export FZF_DEFAULT_OPTS="--preview '$BM --preview {}' --prompt 'bookmark: '"

  # Failsafe if fzf fails/escapes prematurely
  set +e
  BOOKMARK=$(ls -1 "${BOOKMARKS_DIR}" | fzf)
  set -e

  echo "$BOOKMARK"
}

case "$COMMAND" in
  -h|--help)
    echo "bm --version|--expand|--expand-interactive|--preview|--remove|--remove-interactive|--list"
    ;;
  -v|--version)
    echo "bm $BM_VERSION"
    ;;

  -x|--expand|-xi|--expand-interactive)
    if [ "-xi" = "$COMMAND" -o "--expand-interactive" = "$COMMAND" ]; then
      BOOKMARK=$(bm_pick_bookmark)
    else
      BOOKMARK=${2:-}
    fi

    if [ "${BOOKMARK}" = "" ]; then
      echo "."
    else
      readlink -f ${BOOKMARKS_DIR}/${BOOKMARK}
    fi
    ;;

  -r|--remove|-ri|--remove-interactive)
    if [ "-ri" = "$COMMAND" -o "--remove-interactive" = "$COMMAND" ]; then
      BOOKMARK=$(bm_pick_bookmark)
    else
      BOOKMARK=${2:-}
    fi

    if [ "${BOOKMARK}" = "" ]; then
      echo "Nothing to remove"
    else
      rm ${BOOKMARKS_DIR}/${BOOKMARK}
    fi
    ;;

  -p|--preview)
    BOOKMARK="${2:-}"
    RESOLVED="$($BM --expand "${BOOKMARK}")"
    echo "$(tput smul; tput bold)${RESOLVED}$(tput sgr0)"
    $LS -1 "${RESOLVED}"
    ;;

  -l|--list)
    if [ "$LS" = "exa" ]; then
      $LS -1 ${BOOKMARKS_DIR}
    else
      $LS -1 ${BOOKMARKS_DIR} | while read BOOKMARK; do
        echo "${BOOKMARK}: $($BM --resolve "${BOOKMARK}")"
      done
    fi
    ;;

  *|"")
    ln -s "$(realpath .)" "${BOOKMARKS_DIR}/${COMMAND}"
    ;;
esac
